version: "3.8"
services:
  api:
    volumes:
      - ${PWD}/firebase-credentials:/app/firebase-credentials
    env_file:
      - .env
    environment:
      - FIREBASE_SERVICE_ACCOUNT=/app/firebase-credentials/alfred-9fa73-firebase-adminsdk-fbsvc-294854bb8e.json
      - FIREBASE_PROJECT_ID=alfred-9fa73
  
  worker:
    volumes:
      - ${PWD}/firebase-credentials:/app/firebase-credentials
    env_file:
      - .env
    environment:
      - FIREBASE_SERVICE_ACCOUNT=/app/firebase-credentials/alfred-9fa73-firebase-adminsdk-fbsvc-294854bb8e.json
      - FIREBASE_PROJECT_ID=alfred-9fa73
